### ISSUE TITLE
Position in context menu

### ISSUE THREAD

**Issue by uzhne** [alayliercan/SearchwithBookmarks#1]
I would like it to be higher up. Can it be done on the user side? It's locked in place in Menu Wizard. I've read [here](http://forums.mozillazine.org/viewtopic.php?f=48&t=2828771&start=135) that it's because the menu doesn't have a unique id.

**Comment by uzhne** [comment]
Looks like it's unavoidable using SDK and [won't be fixed anytime soon](https://bugzilla.mozilla.org/show_bug.cgi?id=956461). I guess I'll use this hack in the meantime: https://github.com/uzhne/SearchwithBookmarks/commit/e96dda58f6469080c45159359d14d64d462c01cf

**Comment by alayliercan** [comment]
Yes, the Jetpack SDK does not provide an option that targets context-menu position unfortunately. I'm sure they have some good reason for doing so.
I've had a look at the workaround that you found, and made a couple of tests. It seems like it's working but not very efficient. As it uses onMessage event to manipulate the menu position you can see menu jumping over the top in a split second, which isn't nice. It also leaves an unnecessary separator behind where the menu originally was.
All in all, I don't think I'm going to implement this feature in my add-on anytime soon as it wasn't in the plans anyway. Thanks for the feedback though.
